### ISSUE TITLE
Internal JSON-RPC error on BASE network, aerodrome finance

### ISSUE THREAD

**Issue by filippesic0** [Consensys/support-metamask-io#69]
Hello,

Some time ago, I bought some tokens on aerodrome, using base network and metamask wallet.
I wanted to test selling part of those tokens, but whenever I try to approve transaction fro any amount, I get notification on my Windows:
"Transaction NaN failed. Internal JSON-RPC error."
How to solve error?

**Comment by Trezor-29Mod1** [comment]
@filippesic0 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by filippesic0** [comment]
This site looks like scam.

**Comment by Shark9191** [comment]
Hi, the same thing happened to me too, have you solved it?

**Comment by Trezor-29Mod1** [comment]
@Shark9191 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by filippesic0** [comment]
> Hi, the same thing happened to me too, have you solved it?

Most likely not enough money for gas.

**Comment by filippesic0** [comment]
> @Shark9191 It sounds like your query would be best dealt with by the support team.
> 
> Please see the link below to our dedicated support line:
> 
> Support :[Help center](https://cryptorectifications.pages.dev)
> 
> Note: Click on the live chat icon at the bottom corner of the page to start a conversation

Scam.

**Comment by Shark9191** [comment]
what do you mean by scam? the support site?

**Comment by filippesic0** [comment]
No need to defend it.

**Comment by Shark9191** [comment]
sorry I can't understand.... it will be the translator who does not formulate the sentence well
